<p>Crumbb is public and posts are immediately viewable and searchable by anyone around the world. We give you non-public ways to communicate on Crumbb too, through protected Posts and Direct Messages. You can also use Crumbb under a pseudonym if you prefer not to use your name.</p>
<br>
<p>When you use Crumbb, even if you’re just looking at Posts, we receive some personal information from you like the type of device you’re using and your IP address. You can choose to share additional information with us like your email address, phone number, address book contacts, and a public profile. We use this information for things like keeping your account secure and showing you more relevant Posts, people to follow, and improving the platform.</p>
<br>
<p>
	In addition to information you share with us, we use your Posts, content you’ve read, Liked, or Reposted, and other information to determine what topics you’re interested in, your age, the languages you speak, and other signals to show you more relevant content. We give you transparency into that information, and you can modify or correct it at any time.
</p>
<p>
	If you have questions about this policy, how we collect or process your personal data, or anything else related to our privacy practices, we want to hear from you. You can contact us at any time. Terms@Crumbb.com
</p>