<script>
	
	"use strict";

	jQuery(document).ready(function($) {

		const _app = $('div[data-app="trending"]');

		_app.find('button[data-an="load-more"]').on('click', function(event) {
			event.preventDefault();
			var last_li = $('div[data-list-item]').last();
			var _self   = $(this);

			if (last_li.length) {
				$.ajax({
					url: "<?php echo cl_link("native_api/trending/load_more"); ?>",
					type: 'GET',
					dataType: 'json',
					data: {
						offset: last_li.data('list-item'),
					},
					beforeSend: function(){
						_self.attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
					}
				}).done(function(data) {
					if (data.status == 200) {
						_app.find('div[data-an="hashtags-list"]').append(data.html);

						_self.removeAttr('disabled').text("<?php echo cl_translate("Show more"); ?>");
					}

					else {
						_self.text("<?php echo cl_translate("That is all for now!"); ?>");
					}
				});
			}
		});
	});
</script>