<h4>What is Crumbb.</h4>
<p>Crumbb is a service for friends, family, and coworkers to communicate and stay connected through the exchange of quick, frequent messages. Peoples' posts may contain photos, videos, links, and text. These messages are posted to your profile, sent to your followers, and are searchable on Crumbb search.</p>
<br><br>
<h4>Do I need anything special to use it?</h4>
<p>
All you need to use Crumbb is an internet connection or a mobile phone. Join us today! Once you're in, begin finding and following accounts whose posts interest you. We'll recommend great accounts once you're signed up.
</p>
<p>
More FAQs coming soon. 
</p>