<tr>
    <td colspan="7">
        <div class="empty-table">
            <span class="icon">
                <i class="material-icons">report</i>
            </span>
            <h4><?php echo('No reported posts found'); ?></h4>
            <p>
                <?php echo('It looks like there are no reported posts in your database yet. All reported posts of your site will be displayed here.'); ?>
            </p>
        </div>
    </td>
</tr>