<h4>Our use of cookies and similar technologies.</h4>
<p>Our services use cookies and other similar technologies, such as pixels or local storage, to help provide you with a better, faster, and safer experience. Here are some of the ways that our services, including our various websites, SMS, APIs, email notifications, applications, buttons, widgets, and ads, use these technologies: to log you into Crumbb save your preferences, personalize the content you see, protect against spam and abuse.
</p>

<br><br>
<h4>Our services use these technologies to deliver, measure, and improve our services in various ways. These uses generally fall into one of the following categories:</h4>
<p>
 <li>To protect your security.</li>
  <li>To let you to view content with limited distribution.</li>
  <li>To help us detect and fight spam, abuse, and other activities that violate the Crumbb Rules</li>
  <li>To help us improve and understand how people use our services.</li>
</p>
